// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoddcijijjrmksnwsodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZGRjaWppampybWtzbndzb2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODQ2MDEsImV4cCI6MjA1NzI2MDYwMX0.FN_Vg5jGHPsKeTr0AzZcvoEZD6gUAwfE6T7B4LTEDOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});